### ISSUE TITLE
Unable to find version `v1` documentation breaked

### ISSUE THREAD

**Issue by vincent-herlemont** [int128/wait-for-workflows-action#160]
It seems that the action is not reachable; I have followed the `./readme.md`.

```yml
  wait-for-workflows:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: int128/wait-for-workflows-action@v1
        with:
          token: ${{ secrets.PAT }}
```

```bash
Current runner version: '2.311.0'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Error: Unable to resolve action `int1[2](https://github.com/vincent-herlemont/struct_db_private/actions/runs/7307452728/job/19913167545#step:1:2)8/wait-for-workflows-action@v1`, unable to find version `v1`
```
